"""Centralized constants for the traffic simulation."""

PERMANENT_INCIDENT_DURATION = -1

REROUTE_POSITION_THRESHOLD = 8

ACO_DEPOSIT_MULTIPLIER = 0.1
ACO_CONGESTION_PENALTY = 0.5
ACO_INCIDENT_PENALTY = 0.3

CONGESTION_THRESHOLD = 0.7
CONGESTION_CLEAR_THRESHOLD = 0.5

PSO_HIGH_QUEUE_THRESHOLD = 5
PSO_VERY_HIGH_QUEUE_THRESHOLD = 8
PSO_SLOW_MIN_GREEN_THRESHOLD = 25
PSO_LONG_MAX_GREEN_THRESHOLD = 50
PSO_LOW_QUEUE_THRESHOLD = 2
PSO_QUICK_MIN_GREEN = 15

PSO_HIGH_QUEUE_PENALTY = 0.1
PSO_LONG_PHASE_PENALTY = 0.05
PSO_BASELINE_PENALTY = 0.02
PSO_INVALID_CONFIG_PENALTY = 10.0
PSO_QUICK_SWITCH_BONUS = 0.5

SOTL_PSO_SMOOTHING_FACTOR = 0.3
SOTL_SUGGESTION_COOLDOWN = 30
